name: Test
on:
  pull_request:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sudo bash -s -- -b /usr/local/bin/

      - name: Test
        run: task default test

      # build optic binaries. we don't do anything with them yet, but we will soon. building them here
      # to ensure the build process works. since this is a linux-host we only build for linux. eventually,
      # we'll need something building on macos (and windows?) too.
      - name: Build SEA
        run: task pkg:build -- -t node18-linux-x64,node18-linux-arm64
